language: python
python:
- '3.3'
- '3.4'

install: python setup.py install
script: python setup.py test

deploy:
  provider: pypi
  user: kirillsulim
  password:
    secure: hp81rGlphHumEVJcWE6OGflssOxkB15K8u/NkUQR0YDVIZron9/0iH0Bvu3GWBYBdi92/hCkAiVnSjTDlK6FoLZQEZ19pk890TnjcHAjl5rMjwj0OutktrvL1lCuoBO31MzU9AqCRTZXZyBCaqOO4EJYoiTzRFsi94tRY3/d6EWwGpX5EzxDV+RjYpzc32OC7PlrgRT9O96TS6KdCMBkMvJZic4qmITqEMP3ezVZLICD3LlL46dapKMq7tnXvmxj8V8A9ccCccYwr/5C2NNstbU5aHHLn4UOh/p6ujrzi7Xyr4oJE6X6X0vnw0bdiaPlrdbhFxRYn0FmL/AaviJffn9m+BSop+uLVdh1WqKC9iZrNbQ+1S8Q4RhzBYnxn585F2NtMWMuxYcv+gze6f/+Qrqg7vMDocx9oyIVPv6oIbAfNblrVJr7IZz8I+nVe1K8bahNU3Ho0VwXalMkgPkuma7a1HqPp0oEqFIvJ+bQFzvEb/VVLG1D6STE28PbCGL3b/9OE3Mq+EBeZr2LtR9HCJM8nzI0QCqFLZLH3wYaQp8l8U3CMWRri5p7Yfhd+9SNHcbIKYa4ThKu12tYjqYBK5EXTAw5RsmV8AsefsvsKbt8h6mVRkgCfV6RzumnimQVsqbDoQXzUzT8v/USw//RFEfADMRJddT/vyRX+FFkjHU=
  on:
    tags: true
