language: python
python:
- '3.3'
- '3.4'
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: kirillsulim
  password:
    secure: KjcfBdWdnXVYdhzLgw6U9Uyk+36ZtqGY8lI++PueQR/A+7UUD4bxcn4l8Lf4Qmdgfakhxuo3O6nDfXgJj6q7sJ9XBMY4PYKzzF3J8I/008K0/V8Uj5KRCXtw4BPt2T7Wm0qmeKEHAV2CTTwa2G4Ztj7duL/yic3q0xXU1hk1apLmyc1mNk2vzruqEdXTj8sids0ffhMEUvaZtoucim/aFD8iZ7qKDEp5Aneqnxz/gQLGmg63RulS/BXc0lmb+vDdHcMDzIjbtac6y4y/hFEt/RN9ZlStqtONrg840WYTrRnLvAELetccZaScIEbPBpRUht5NBHEDrkTAXgiF5LaMzxF8pRZX+3tDIfisYR3xirmCkwa6Yt71R2RGpHRlti+GMEhxUxpOEsCoByfnatBlngARl5DNJviYUIxnahavBWqQ/OSCawgZw/Jq0IHQE2oLjAkb77q/kZxNDP8Wc/2Ggkr+Tcltiry+ue6BBL+dg2jx0+aeg58CqgHMc47T/QNF1WGjG+/RMYLTyaw2oy+WhPVBSEiKr02KN+JOgB+UX/hQ9v8oIAUURGnaBIWlfnD71hFUHUN3wgTVNvfmMdkCUqrmlGCqZnPVO3eAKmaUoleVSjjeWXnxn50Zr+g490fyNNbHezuo0wcCzZzJajCM/S58BW04oonxZwpdM2yH5QU=
  on:
    tags: true
    repo: dogebuild/dogebuild
